apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: 004447353381.dkr.ecr.us-east-1.amazonaws.com/emailservice:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080