apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailapi
  labels:
    app: emailapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailapi
  template:
    metadata:
      labels:
        app: emailapi
    spec:
      containers:
        - name: emailapi
          image: 004447353381.dkr.ecr.us-east-1.amazonaws.com/emailapi:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080